version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/php:7.4-apache-buster
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y unzip
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: composer install --no-scripts --no-interaction
      - run: vendor/bin/phpunit
